config/routes.rb
LearningShelter::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'basic#events', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
	#namespace :dashboard
  match 'dashboard' => 'dashboard#index'
# calendar
  #match 'calendar/events/new' => 'events#new' # link


# /admin
  get '/admin/mailer' => 'admin/mailer#send'
  post '/admin/mailer' => 'admin/mailer#send_mail'
  match '/admin' => 'admin#index'
  match '/admin/acceptClient/:id' => 'admin#acceptClient'
  match '/admin/acceptVol/:id' => 'admin#acceptVol'
  namespace :admin do
    resources :apps
  end
  match 'admin/calendar' => 'admin/calendar#index' # link
  namespace :admin do
    namespace :calendar do
      resources :events
    end
  end

#  get "basic/index"
  resources :home
  root :to => "home#index"
  get '/index' => "home#index", :as => 'index'
  match "/about" => "basic#about"
  match "/events" => "basic#events"
  match "/signup" => "basic#signup"
  match "/donate" => "basic#donate"
  
  match 'dashboard/application/cl' => 'application#apply_client' # link
  match 'dashboard/calendar' => 'dashboard/calendar#index' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :clients
    end
    namespace :calendar do
       resources :events
    end	
  end	
 
  match 'dashboard/application/vol' => 'application#apply_volunteer' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :volunteers
    end
  end	

  #ERROR
  match '*a', :to => 'errors#routing'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :end_at, :start_at, :location, :description, :user_id, :color
  has_event_calendar
  belongs_to :user
end

app/controllers/admin/calendar/events_controller.rb
class Admin::Calendar::EventsController < ApplicationController
  include EventHashHelper
	def edit
		@event = Event.find(params[:id])
	end
	
	def new
	end

  def show
    @event = Event.find(params[:id])
    if request.xhr?
     	render :partial => 'show', :object=> @event 
    end
  end

  def create
    self.setNewPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      self.createEvent
    end
  end

  def update
    @event = Event.find params[:id]
    self.setEditPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      @event.update_attributes!(@eventhash)
    flash[:notice] = "#{@event.name} was successfully updated."
    redirect_to admin_calendar_event_path(@event)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "event '#{@event.name}' deleted."
    redirect_to admin_calendar_path
  end
	
end

app/controllers/admin/calendar_controller.rb
class Admin::CalendarController < ApplicationController
  before_filter :authenticate_admin!
  include GetEventsHelper
  def index
    self.getEvents
  end
  
end

app/controllers/dashboard/calendar/events_controller.rb
class Dashboard::Calendar::EventsController < ApplicationController
  include EventHashHelper
  def edit
    @event = Event.find(params[:id])
  end

  def new
  end

  def show
    @event = Event.find(params[:id])
    if request.xhr?
      render :partial => 'show', :object=> @event 
    end
  end

  def create
    self.setNewPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      self.createEvent
    end
  end

  def update
    @event = Event.find params[:id]
    self.setEditPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      @event.update_attributes!(@eventhash)
      flash[:notice] = "#{@event.name} was successfully updated."
      redirect_to dashboard_calendar_event_path(@event)
    end  
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "event '#{@event.name}' deleted."
    redirect_to dashboard_calendar_path
  end
  
end

app/controllers/dashboard/calendar_controller.rb
class Dashboard::CalendarController < ApplicationController
  before_filter :authenticate_user!  
  include GetEventsHelper
  def index  
    self.getEvents 
  end
  
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end


  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      if(current_user.try(:admin?))
      	link_to "#{event.name}",  admin_calendar_event_path(event.id), :remote => true
     else
	link_to "#{event.name}",  dashboard_calendar_event_path(event.id), :remote => true
     
     end
     # %(<a href="calendar/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
 def isOwner?
   @event.user_id == current_user.id
 end

 def isAdminEvent?
   User.find(@event.user_id).admin
 end
 
  def isLoggedIn?
   user_signed_in?
 end

 def displayEventTime(eventTime)
  ((eventTime != "") && (eventTime != nil)) ? eventTime.strftime('%l:%M %P') : 'hh/mm am'
 end

 def displayEventDate(eventDate)
  ((eventDate != "") && (eventDate != nil)) ? eventDate.strftime('%m/%d/%Y') : 'mm/dd/yyyy'
 end

 def prettifyEventDate(eventTime)
   eventTime.strftime('%A %d, %B at %l:%M %P')
 end

 def checkEvent(field)
  return @event ? @event.send(field) : ""
 end

 def checkSession(field)
  return session[:event] ? session[:event][field.parameterize.underscore.to_s] : nil
 end

 def setValue(field)
   value = checkSession(field)
   value ||= checkEvent(field)
 end

 def setTime(field) 
    value = checkSession(field.gsub("at","time"))
    value ||= displayEventTime checkEvent(field)    
 end

 def setDate(field)
    value = checkSession(field.gsub("at","date"))   
    value ||= displayEventDate checkEvent(field) 
    
 end
end

app/views/admin/calendar/events/_show.html.haml
.body
  .mainform
    %h2 Admin Details about #{@event.name}
    %ul#details
      %li
        Start Time:
        = prettifyEventDate(@event.start_at)
      %li
        End Time:
        = prettifyEventDate(@event.end_at)
      %li
        Location:
        = @event.location

    %h3 Description:

    %p#description= @event.description
    - if isOwner?
      = link_to 'Edit', edit_admin_calendar_event_path(@event)
      = button_to 'Delete', admin_calendar_event_path(@event), :method => :delete, :confirm => 'Are you sure?'

app/views/admin/calendar/events/edit.html.haml
.body
  .mainform
    %h1 Admin Edit Event
    = form_tag admin_calendar_event_path, :method => :put do
      = render :partial => 'shared/event_form', :object => @event 
      %p
        = submit_tag 'Save Changes'

app/views/admin/calendar/events/new.html.haml
.body
  .mainform
    %h1 Add New Event
    = form_tag admin_calendar_events_path, :method => :post do
      = render :partial => 'shared/event_form'
      %p
        = submit_tag 'Save Event'

app/views/admin/calendar/events/show.html.haml
.body
  .mainform
    %h2 Admin Details about #{@event.name}
    %ul#details
      %li
        Start Time:
        = prettifyEventDate(@event.start_at)
      %li
        End Time:
        = prettifyEventDate(@event.end_at)
      %li
        Location:
        = @event.location

    %h3 Description:

    %p#description= @event.description
    -if isOwner?
      = link_to 'Edit', edit_admin_calendar_event_path(@event)
      = button_to 'Delete', admin_calendar_event_path(@event), :method => :delete, :confirm => 'Are you sure?'
    = link_to 'Back to calendar', admin_calendar_path