config/routes.rb
LearningShelter::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'basic#events', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
	#namespace :dashboard
  match 'dashboard' => 'dashboard#index'
# calendar
  #match 'calendar/events/new' => 'events#new' # link


# /admin
  get '/admin/mailer' => 'admin/mailer#send'
  post '/admin/mailer' => 'admin/mailer#send_mail'
  match '/admin' => 'admin#index'
  match '/admin/acceptClient/:id' => 'admin#acceptClient'
  match '/admin/acceptVol/:id' => 'admin#acceptVol'
  namespace :admin do
    resources :apps
  end
  match 'admin/calendar' => 'admin/calendar#index' # link
  namespace :admin do
    namespace :calendar do
      resources :events
    end
  end

#  get "basic/index"
  resources :home
  root :to => "home#index"
  get '/index' => "home#index", :as => 'index'
  match "/about" => "basic#about"
  match "/events" => "basic#events"
  match "/signup" => "basic#signup"
  match "/donate" => "basic#donate"
  
  match 'dashboard/application/cl' => 'application#apply_client' # link
  match 'dashboard/calendar' => 'dashboard/calendar#index' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :clients
    end
    namespace :calendar do
       resources :events
    end	
  end	
 
  match 'dashboard/application/vol' => 'application#apply_volunteer' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :volunteers
    end
  end	

  #ERROR
  match '*a', :to => 'errors#routing'

end

app/controllers/basic_controller.rb
class BasicController < ApplicationController
  def index
  end

  def events
   @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    #@event_strips = Event.event_strips_for_month(@shown_month)

    @start_d, @end_d = Event.get_start_and_end_dates(@shown_month) # optionally pass in @first_day_of_week
    @events = Event.events_for_date_range(@start_d, @end_d)
    @events.reject! { |event|
      not (isAdminEvent?(event))
    }
    @event_strips = Event.create_event_strips(@start_d, @end_d, @events)
  end 
end

app/helpers/basic_helper.rb
module BasicHelper
include CalendarHelper
end

app/views/basic/about.html.erb
	<div class="tabContent" id="events">
    <div class='tabtext'>

      <h3>About The Learning Shelter</h3>
			  <p>The Vision of The Learning Shelter is to become a shelter system by example. As the first model we are testing the ideas which will become a live in/work in program built to allow individuals who seem to be qualified and have been skills tested to show an aptitude for making products both digital and tangible. Once qualified, cohorts will work as individuals among groups to find their own pace and channels then be guided through accelerated learning programs that teach skills which are currently relevant, less likely to be crowded by unemployed experts, and which have highly probable future viability.</p>
			  <p>The Learning Shelter is currently planning out the due diligence process with some San Francisco based California 501(c)(3) non-profit corporations, in the hopes of finding a responsible and experienced home base that will sufficiently allow the project to grow into it's own non-profit in 2014.</p>
			  <p><h3 style='display:inline'>Our Motto:</h3> Our job is to put ourselves out of jobs by creating graduates that don't come back.</p>
			  <p>We hope to find partner companies that can both provide training using real world products of innovative design as well as hopefully employ and encourage our graduates after they have completed a 90 day program. It is very possible that this partners can go beyond employment over a short number of years and even incubate or fund some creative new business ideas. The reality of these ideas are yet to be tested, but the hope is strong.</p>
			  <p>Through community alliances with other non-profits The Learning Shelter can make a difference in the life of anyone who is homeless if we can reduce the resource draw and increase the volume of tax paying citizens in a local economy. So while we aren't a solution for every kind of homeless person, we are ultimately going to be able to make an impact that will help not only the entire homeless community, but ultimately the entire community around The Learning Shelter.</p>


      <h3>Our Goals:</h3>
			  <p>Expose learners to possibilities via hands on experience with various technologies including; 3D printing, laser cutting, welding, CAD Design, Web Design and Development</p>
			  <p>Empower learners to develop a physical and digital identity</p>
			  <p>Provide a daily structure for learners to develop technical and interpersonal skills</p>
			  <p>Enable learners to build and present hardware or software prototypes</p>
			  <p>Assist learners with setting goals for personal and professional development</p>

    </div>
	</div>

app/views/basic/donate.html.erb
  <div class="tabContent" id="donate">
    <div class='tabtext'>
      <h3>Donate</h3>
		  <h3>Why Learning Shelter?</h3>
      <p>Coming up soon</p>
    </div>
  </div>

app/views/basic/events.html.erb
	<div class="tabContent" id="events">
    <div class='tabtext'>
		  <h3>Upcoming Events:
		  
		  <%= raw(event_calendar) %>
		  </h3>
    </div>
	</div>

app/views/basic/index.html.erb
<h1>The learning Shelter (in views/basic/index.html.erb)</h1>
The Learning Shelter

<div>Tabs: about, sign up, login</div>
<div>"The Learning Shelter is creating a template for skill building, education and community engagement."</div>
<div>"The Learning Shelter exposes possibilities, mentors, participants, teaches viable techinical skills and empowers marginalized populations to achieve personal sustainability and create opportunities for their communities."</div>
<%= link_to "about", about_path %>




<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>

<h2>extra</h2>

<%= render "devise/shared/links/signin" %>

app/views/basic/signup.html.erb
  <div class="tabContent" id="signup">
    <div class='tabtext'>
		  <h3>Sign up</h3>
		  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
			  <%= devise_error_messages! %>
			  <div class='left'><%= f.label :email %></div>
			  <div class='right'><%= f.email_field :email %></div>
			  <div class='left'><%= f.label :password %></div>
			  <div class='right'><%= f.password_field :password %></div>
			  <div class='left'><%= f.label :password_confirmation %></div>
			  <div class='right'>
          <%= f.password_field :password_confirmation %>
          <p><%= f.submit "Sign up", :class => "myButton", :onclick=>"return validateSignUpForm();" %></p>
        </div>
		  <% end %>
		  <!-- newlines for height fit -->
		  <br><br><br><br><br>
		  <br><br><br><br><br> 
    </div>
  </div>