config/routes.rb
LearningShelter::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'basic#events', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
	#namespace :dashboard
  match 'dashboard' => 'dashboard#index'
# calendar
  #match 'calendar/events/new' => 'events#new' # link


# /admin
  get '/admin/mailer' => 'admin/mailer#send'
  post '/admin/mailer' => 'admin/mailer#send_mail'
  match '/admin' => 'admin#index'
  match '/admin/acceptClient/:id' => 'admin#acceptClient'
  match '/admin/acceptVol/:id' => 'admin#acceptVol'
  namespace :admin do
    resources :apps
  end
  match 'admin/calendar' => 'admin/calendar#index' # link
  namespace :admin do
    namespace :calendar do
      resources :events
    end
  end

#  get "basic/index"
  resources :home
  root :to => "home#index"
  get '/index' => "home#index", :as => 'index'
  match "/about" => "basic#about"
  match "/events" => "basic#events"
  match "/signup" => "basic#signup"
  match "/donate" => "basic#donate"
  
  match 'dashboard/application/cl' => 'application#apply_client' # link
  match 'dashboard/calendar' => 'dashboard/calendar#index' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :clients
    end
    namespace :calendar do
       resources :events
    end	
  end	
 
  match 'dashboard/application/vol' => 'application#apply_volunteer' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :volunteers
    end
  end	

  #ERROR
  match '*a', :to => 'errors#routing'

end

app/views/admin/acceptClient.erb
<h1>  </h1>


	

app/views/admin/acceptVol.erb
<h1>  </h1>


	

app/views/admin/index.html.erb
<%= stylesheet_link_tag "admin_style" %>

<body id='admin_body'>

<div id='adminpage'>


  <div class="learningShelterLogo", align="right"> 
    <%= image_tag("logo_wrench_bed.png") %>
  </div>
  <h1>Welcome to Admin Page</h1>
  </br>
  </br>
  <h2><%= link_to "- Admin Calendar", admin_calendar_path %></h2>
  <h2><%= link_to "- Send E-mail", admin_mailer_path %></h2>
  </br>
  </br>
  </br>


  <ul id="list">
    <li><a href="#users">Current Users</a></li>
    <li><a href="#clients">Program Application</a></li>
    <li><a href="#volunteers">Volunteer Application</a></li>
  </ul>
  </br>
  </br>

  <div class="contents">
  <div class="content", id="users">
    <div id="tablewrapper">
      <div id="tableheader">
        <div class="search">
          <select id="columns" onchange="sorter.search('query')"></select>
          <input type="text" id="query" onkeyup="sorter.search('query')" />
        </div>
        <span class="details">
	  <div>Records <span id="startrecord"></span>-<span id="endrecord"></span> of <span id="totalrecords"></span></div>
          <div><a href="javascript:sorter.reset()">reset</a></div>
        </span>
      </div>

      <table cellpadding="0" cellspacing="0" border="0" id="table" class="tinytable">
        <thead>
          <tr>
            <th class="nosort"><h3>User ID</h3></th>
            <th><h3>User E-mail</h3></th>
            <th><h3>Status</h3></th>
            <th><h3>User Application</h3></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
  	    <td><%= user.id %> </td>
	    <td><%= user.email %></td>
            <td><%= user.status %></td>
	    <% if user.apps.find_by_user_id(user_id=user.id) %>
	    <td><%= link_to "Application Details", admin_app_path(user.apps.find_by_user_id(user_id=user.id)) %></td>  
	    <% end %>
	  </tr>
          <% end %>
        </tbody>
      </table>

      <div id="tablefooter"> 
        <div id="tablenav">
          <div> 
            <%= link_to image_tag("table/first.gif"), :onclick => "sorter.move(-1,true)" %>
            <%= link_to image_tag("table/previous.gif"), :onclick => "sorter.move(-1)" %>
            <%= link_to image_tag("table/next.gif"), :onclick => "sorter.move(1)" %>
            <%= link_to image_tag("table/last.gif"), :onclick => "sorter.move(1,true)" %>
          </div>
          <div>
            <select id="pagedropdown"></select>
	  </div>
          <div>
            <a href="javascript:sorter.showall()">view all</a>
          </div>
        </div>
	<div id="tablelocation">
          <div>
            <select onchange="sorter.size(this.value)">
              <option value="5">5</option>
              <option value="10" selected="selected">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
            <span>Entries Per Page</span>
          </div>
          <div class="page">Page <span id="currentpage"></span> of <span id="totalpages"></span></div>
        </div>
      </div>
    </div>
  </div>




  <div class="content", id="clients">
   <!--  <div id="tablewrapper">
      <div id="tableheader">
        <div class="search">
          <select id="columns" onchange="sorter.search('query')"></select>
          <input type="text" id="query" onkeyup="sorter.search('query')" />
        </div>
        <span class="details">
	  <div>Records <span id="startrecord"></span>-<span id="endrecord"></span> of <span id="totalrecords"></span></div>
          <div><a href="javascript:sorter.reset()">reset</a></div>
        </span>
      </div> -->

      <table cellpadding="0" cellspacing="0" border="0" id="table" class="tinytable">
        <thead>
          <tr>
	    <th><h3>First Name</h3></th>
	    <th><h3>Last Name</h3></th>
	    <th><h3>Gender</h3></th>
	    <th><h3>Birthday</h3></th>
	    <th><h3>Phone Number</h3></th>
	    <th><h3>Street Address</h3></th>
	    <th><h3>City</h3></th>
	    <th><h3>State</h3></th>
	    <th><h3>User ID</h3></th>
	    <th><h3>Submission Time</h3></th>
            <th><h3>Accepted?</h3></th>
            <th><h3>Decision</h3></th>   
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
          <tr>
	    <td><%= client.first_name %> </td>
	    <td><%= client.last_name %></td>
	    <td><%= client.gender %></td>
	    <td><%= client.birthday %></td>
	    <td><%= client.phone %> </td>
	    <td><%= client.street_address %></td>
            <td><%= client.city %> </td>
	    <td><%= client.state %></td>
	    <td><%= client.user_id %></td>
	    <td><%= client.created_at %></td>
	    <td><%= client.accepted %></td>
	    <td><%= button_to "Accept this app", :action => "acceptClient", :id => client.id %></td>
	  </tr>
          <% end %>
        </tbody>
      </table>

      <!-- <div id="tablefooter"> 
        <div id="tablenav">
          <div> 
            <%= link_to image_tag("table/first.gif"), :onclick => "sorter.move(-1,true)" %>
            <%= link_to image_tag("table/previous.gif"), :onclick => "sorter.move(-1)" %>
            <%= link_to image_tag("table/next.gif"), :onclick => "sorter.move(1)" %>
            <%= link_to image_tag("table/last.gif"), :onclick => "sorter.move(1,true)" %>
          </div>
          <div>
            <select id="pagedropdown"></select>
	  </div>
          <div>
            <a href="javascript:sorter.showall()">view all</a>
          </div>
        </div>
	<div id="tablelocation">
          <div>
            <select onchange="sorter.size(this.value)">
              <option value="5">5</option>
              <option value="10" selected="selected">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
            <span>Entries Per Page</span>
          </div>
          <div class="page">Page <span id="currentpage"></span> of <span id="totalpages"></span></div>
        </div>
      </div>
    </div> -->
  </div>



  <div class="content", id="volunteers">
    <!-- <div id="tablewrapper">
      <div id="tableheader">
        <div class="search">
          <select id="columns" onchange="sorter.search('query')"></select>
          <input type="text" id="query" onkeyup="sorter.search('query')" />
        </div>
        <span class="details">
	  <div>Records <span id="startrecord"></span>-<span id="endrecord"></span> of <span id="totalrecords"></span></div>
          <div><a href="javascript:sorter.reset()">reset</a></div>
        </span>
      </div> -->

      <table cellpadding="0" cellspacing="0" border="0" id="table" class="tinytable">
        <thead>
          <tr>
	    <th><h3>First Name</h3></th>
	    <th><h3>Last Name</h3></th>
	    <th><h3>Gender</h3></th>
	    <th><h3>Birthday</h3></th>
	    <th><h3>Phone Number</h3></th>
	    <th><h3>Street Address</h3></th>
	    <th><h3>City</h3></th>
	    <th><h3>State</h3></th>
	    <th><h3>User ID</h3></th>
	    <th><h3>Submission Time</h3></th>
            <th><h3>Accepted?</h3></th>
            <th><h3>Decision</h3></th> 
          </tr>
        </thead>
        <tbody>
          <% @volunteers.each do |volunteer| %>
          <tr>
	    <td><%= volunteer.first_name %> </td>
	    <td><%= volunteer.last_name %></td>
	    <td><%= volunteer.gender %></td>
	    <td><%= volunteer.birthday %></td>
	    <td><%= volunteer.phone %> </td>
	    <td><%= volunteer.street_address %></td>
            <td><%= volunteer.city %> </td>
	    <td><%= volunteer.state %></td>
	    <td><%= volunteer.user_id %></td>
	    <td><%= volunteer.created_at %></td>
            <td><%= volunteer.accepted %></td>
            <td><%= button_to "Accept this app", :action => "acceptVol", :id => volunteer.id %></td>
	  </tr>
          <% end %>
        </tbody>
      </table>

      <!-- <div id="tablefooter"> 
        <div id="tablenav">
          <div> 
            <%= link_to image_tag("table/first.gif"), :onclick => "sorter.move(-1,true)" %>
            <%= link_to image_tag("table/previous.gif"), :onclick => "sorter.move(-1)" %>
            <%= link_to image_tag("table/next.gif"), :onclick => "sorter.move(1)" %>
            <%= link_to image_tag("table/last.gif"), :onclick => "sorter.move(1,true)" %>
          </div>
          <div>
            <select id="pagedropdown"></select>
	  </div>
          <div>
            <a href="javascript:sorter.showall()">view all</a>
          </div>
        </div>
	<div id="tablelocation">
          <div>
            <select onchange="sorter.size(this.value)">
              <option value="5">5</option>
              <option value="10" selected="selected">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
            <span>Entries Per Page</span>
          </div>
          <div class="page">Page <span id="currentpage"></span> of <span id="totalpages"></span></div>
        </div>
      </div>
    </div> -->
  </div>





	

  </div>
</body>
<script type="text/javascript" src="script.js"></script>
	<script type="text/javascript">
	var sorter = new TINY.table.sorter('sorter','table',{
		headclass:'head',
		ascclass:'asc',
		descclass:'desc',
		evenclass:'evenrow',
		oddclass:'oddrow',
		evenselclass:'evenselected',
		oddselclass:'oddselected',
		paginate:true,
		size:10,
		colddid:'columns',
		currentid:'currentpage',
		totalid:'totalpages',
		startingrecid:'startrecord',
		endingrecid:'endrecord',
		totalrecid:'totalrecords',
		hoverid:'selectedrow',
		pageddid:'pagedropdown',	
		sortcolumn:1,
		sortdir:1,
		sum:[8],
		avg:[6,7,8,9],
		columns:[{index:7, format:'%', decimals:1},{index:8, format:'$', decimals:0}],
		init:true
	});
  </script>	

  


 