config/routes.rb
LearningShelter::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'basic#events', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
	#namespace :dashboard
  match 'dashboard' => 'dashboard#index'
# calendar
  #match 'calendar/events/new' => 'events#new' # link


# /admin
  get '/admin/mailer' => 'admin/mailer#send'
  post '/admin/mailer' => 'admin/mailer#send_mail'
  match '/admin' => 'admin#index'
  match '/admin/acceptClient/:id' => 'admin#acceptClient'
  match '/admin/acceptVol/:id' => 'admin#acceptVol'
  namespace :admin do
    resources :apps
  end
  match 'admin/calendar' => 'admin/calendar#index' # link
  namespace :admin do
    namespace :calendar do
      resources :events
    end
  end

#  get "basic/index"
  resources :home
  root :to => "home#index"
  get '/index' => "home#index", :as => 'index'
  match "/about" => "basic#about"
  match "/events" => "basic#events"
  match "/signup" => "basic#signup"
  match "/donate" => "basic#donate"
  
  match 'dashboard/application/cl' => 'application#apply_client' # link
  match 'dashboard/calendar' => 'dashboard/calendar#index' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :clients
    end
    namespace :calendar do
       resources :events
    end	
  end	
 
  match 'dashboard/application/vol' => 'application#apply_volunteer' # link
  #CRUD
  namespace :dashboard do
    namespace :application do
      resources :volunteers
    end
  end	

  #ERROR
  match '*a', :to => 'errors#routing'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

 def isOwner?(event) 
   event.user_id == current_user.id
 end

 def isAdminEvent?(event)
   User.find(event.user_id).admin
 end

 def isLoggedIn?
   user_signed_in?
 end

 def authenticate_admin!
   if current_user.try(:admin?)
     #do nothing
   else
     flash[:notice] = "You do not have the authorization to access this page"
     redirect_to '/dashboard'
   end
 end
end

app/controllers/dashboard/application/clients_controller.rb
class Dashboard::Application::ClientsController < ApplicationController
  def create
    client_app = Client.create!(params[:client])
    if current_user.apps.none?
    	current_user.apps << client_app
      flash[:notice] = "A new Client Application has been submitted!"
      redirect_to '/dashboard'
    else
      flash[:notice] = "You have already submitted a Client Application."
      redirect_to '/dashboard'
    end
    
  end
  def index
  	@clients = Client.all
  end
end

app/controllers/dashboard/application/volunteers_controller.rb
class Dashboard::Application::VolunteersController < ApplicationController
  def create
    volunteer_app = Volunteer.create!(params[:volunteer])
    if current_user.apps.none?
    	current_user.apps << volunteer_app
      flash[:notice] = "A new Volunteer Application has been submitted!"
      redirect_to '/dashboard'
    else
      flash[:notice] = "You have already submitted a Volunteer Application."
      redirect_to '/dashboard'
    end
    
  end
  def index
  	@volunteers = Volunteer.all
  end
end

app/controllers/dashboard/calendar/events_controller.rb
class Dashboard::Calendar::EventsController < ApplicationController
  include EventHashHelper
  def edit
    @event = Event.find(params[:id])
  end

  def new
  end

  def show
    @event = Event.find(params[:id])
    if request.xhr?
      render :partial => 'show', :object=> @event 
    end
  end

  def create
    self.setNewPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      self.createEvent
    end
  end

  def update
    @event = Event.find params[:id]
    self.setEditPaths
    self.updateSessionParams
    @eventhash = self.setUpEventHash
    if(self.validate)
      @event.update_attributes!(@eventhash)
      flash[:notice] = "#{@event.name} was successfully updated."
      redirect_to dashboard_calendar_event_path(@event)
    end  
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "event '#{@event.name}' deleted."
    redirect_to dashboard_calendar_path
  end
  
end

app/controllers/dashboard/calendar_controller.rb
class Dashboard::CalendarController < ApplicationController
  before_filter :authenticate_user!  
  include GetEventsHelper
  def index  
    self.getEvents 
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_filter :authenticate_user!
  def index

  end

  def show
  
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/application/apply_client.html.haml
%h1 Apply to be a Client

= form_tag dashboard_application_clients_path do

  = label :client, :first_name, 'First Name'
  = text_field :client, 'first_name'
  %br

  = label :client, :last_name, 'Last Name'
  = text_field :client, 'last_name'
  %br

  /make to checkbox?
  = label :client, :gender, 'Gender' 
  = text_field :client, 'gender'
  %br

  = label :client, :birthday, 'Birthday'
  = date_select :client, :birthday
  %br

  = label :client, :phone, 'Phone number' 
  = text_field :client, 'phone'
  %br

  = label :client, :street_address, 'Street Address' 
  = text_field :client, 'street_address'
  %br

  = label :client, :city, 'City' 
  = text_field :client, 'city'
  %br
  = label :client, :state, 'State' 
  = text_field :client, 'state'
  %br

  = submit_tag 'Apply'

app/views/dashboard/application/apply_volunteer.html.haml
.mainform
  %h1 Apply to be a Volunteer

  = form_tag dashboard_application_volunteers_path do

    = label :volunteer, :first_name, 'First Name'
    = text_field :volunteer, 'first_name'
    %br

    = label :volunteer, :last_name, 'Last Name'
    = text_field :volunteer, 'last_name'
    %br

    /make to checkbox?
    = label :volunteer, :gender, 'Gender' 
    = text_field :volunteer, 'gender'
    %br

    = label :volunteer, :birthday, 'Birthday'
    = date_select :volunteer, :birthday
    %br

    = label :volunteer, :phone, 'Phone number' 
    = text_field :volunteer, 'phone'
    %br

    = label :volunteer, :street_address, 'Street Address' 
    = text_field :volunteer, 'street_address'
    %br

    = label :volunteer, :city, 'City' 
    = text_field :volunteer, 'city'
    %br
    = label :volunteer, :state, 'State' 
    = text_field :volunteer, 'state'
    %br

    = submit_tag 'Apply'